server:
  port: '9080'
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ON_PARAM
    include-exception: false

aws:
  region: sa-east-1
  accesskey: '000000'
  secretkey: '000000'
  dynamodb:
    endpoint: http://localhost:4566
